name: System Test

on:
  push:
    branches:
    - main
    - test/**
  pull_request:
      branches:
      - main

jobs:
  systemtest:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SSI-Service Repo
      uses: actions/checkout@v3
      with:
        repository: TBD54566975/ssi-service
        path: ssi-service
        
    - name: Checkout DWN-Relay Repo
      uses: actions/checkout@v3
      with:
        ref: test/dnw-steelthread-test
        repository: TBD54566975/dwn-relay
        path: dwn-relay

    # Setup and seed the ssi-service data
    - name: Start SSI-Service Container
      run: docker-compose -f "ssi-service/build/docker-compose.yml" up -d --build
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Install Mage
      working-directory: ./ssi-service
      run: go install github.com/magefile/mage

    - name: End To End Test And Seed Data
      working-directory: ./ssi-service
      run: mage integration steelthread
      
    - name: Curl Test
      run: curl http://localhost:8080/readiness
      
    # Setup DWN-Relay and run end to end testsz
    - name: Start DWN-Relay Container
      run: docker-compose -f "dwn-relay/docker-compose.yml" up -d --build

    - name: Curl Test DWN-Relay 1
      run: curl http://localhost:9001
      
    - name: Curl Test DWN-Relay 2
      run: curl http://localhost:9000
      
    - name: Install Packages for Test
      working-directory: ./dwn-relay
      run: npm install
    
    - name: Run DWN-Relay End To End Test
      working-directory: ./dwn-relay
      run: node --es-module-specifier-resolution=node src/sanity-checks/protocols-configure-test.js && node --es-module-specifier-resolution=node src/sanity-checks/steelthread-test.js

    - name: Stop SSI-Service Container
      if: always()
      run: docker-compose -f "ssi-service/build/docker-compose.yml" down
      
    - name: Stop DWN-Relay Container
      if: always()
      run: docker-compose -f "dwn-relay/docker-compose.yml" down
