name: System Test

on:
  push:
    branches:
    - main
    - test/**
  pull_request:
      branches:
      - main

jobs:
  systemtest:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ssi-service repo
      uses: actions/checkout@v3
      with:
        repository: TBD54566975/ssi-service
        path: ssi-service
        
    - name: Checkout dwn-relay repo
      uses: actions/checkout@v3
      with:
        ref: test/docker-compose-2
        repository: TBD54566975/dwn-relay
        path: dwn-relay

    - name: Start dwn-relay container
      run: docker-compose -f "dwn-relay/docker-compose.yml" up -d --build
#     - name: Install nodejs
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18
        
#     - name: Start dwn-relay
#       working-directory: ./dwn-relay
#       run: npm install && npm start
    
    - name: Run dwn-relay teset
      working-directory: ./dwn-relay
      run: node --es-module-specifier-resolution=node src/sanity-checks/protocols-configure-test.js && node --es-module-specifier-resolution=node src/sanity-checks/collections-write-test.js

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Install Mage
      working-directory: ./ssi-service
      run: go install github.com/magefile/mage

    - name: Start containers
      run: docker-compose -f "ssi-service/build/docker-compose.yml" up -d --build

    - name: End To End Test
      working-directory: ./ssi-service
      run: mage integration steelthread

    - name: Stop containers
      if: always()
      run: docker-compose -f "ssi-service/build/docker-compose.yml" down
