name: System Test

on:
  push:
    branches:
    - main
    - test/**
  pull_request:
      branches:
      - main

jobs:
  end2endtest:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: TBD54566975/ssi-service
        path: ssi-service

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Install Mage
      run: go install github.com/magefile/mage

    - name: Start containers
      run: docker-compose -f "ssi-service/build/docker-compose.yml" up -d --build

    - name: End To End Test
      run: mage integration steelthread

    - name: Stop containers
      if: always()
      run: docker-compose -f "ssi-service/build/docker-compose.yml" down
